r1_values = map(int, raw_input().split())
p1_values = map(int, raw_input().split())
p2_values = map(int, raw_input().split())
A, B = map(int, raw_input().split())
r1 = max(r1_values[1:])
p1 = max(p1_values[1:])
p2 = min(p2_values[1:])
r2 = pow(r1,2) * ((p1*B)*1.0/(p1*B + p2*A))
print pow(r2, 0.5)